format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$fill\
$cmd_duration\
$time\
$line_break\
$jobs\
$battery\
$status\
$os\
$container\
$shell\
$character"""

[fill]
symbol = " "

[time]
disabled = false
format = ' [$time]($style)'

[aws]
symbol = '  '
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'

[buf]
symbol = ' '

[c]
symbol = ' '
format = '\[[$symbol($version(-$name))]($style)\]'

[conda]
symbol = ' '
format = '\[[$symbol$environment]($style)\]'

[dart]
symbol = ' '
format = '\[[$symbol($version)]($style)\]'

[directory]
read_only = ' '
# Dispaly full path instead of just folder
truncation_length = 0
truncate_to_repo = false

[docker_context]
symbol = ' '
format = '\[[$symbol$context]($style)\]'

[elixir]
symbol = ' '
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'

[elm]
symbol = ' '
format = '\[[$symbol($version)]($style)\]'

[fossil_branch]
symbol = ' '
format = '\[[$symbol$branch]($style)\]'

[git_branch]
# symbol = ' '
symbol = ' '
format = '\[[$symbol$branch(:$remote_branch)]($style)\]'
always_show_remote = true

[git_commit]
format = '\[[$hash$tag]($style)'
tag_disabled = false
tag_symbol = '  '

[git_metrics]
disabled = false
format = '(\[([+$added]($added_style))( [-$deleted]($deleted_style))\])'

[git_status]
diverged = "󰹺"
# behind = ""
# ahead = ""

[golang]
symbol = ' '
format = '\[[$symbol($version)]($style)\]'

[guix_shell]
symbol = ' '
format = '\[[$symbol]($style)\]'

[haskell]
symbol = ' '
format = '\[[$symbol($version)]($style)\]'

[haxe]
symbol = '⌘ '
format = '\[[$symbol($version)]($style)\]'

[hg_branch]
symbol = ' '
format = '\[[$symbol$branch]($style)\]'

[java]
symbol = ' '
format = '\[[$symbol($version)]($style)\]'

[julia]
symbol = ' '
format = '\[[$symbol($version)]($style)\]'

[lua]
symbol = ' '
format = '\[[$symbol($version)]($style)\]'

[memory_usage]
symbol = ' '
format = '\[$symbol[$ram( | $swap)]($style)\]'

[meson]
symbol = '喝 '
format = '\[[$symbol$project]($style)\]'

[nim]
symbol = ' '
format = '\[[$symbol($version)]($style)\]'

[nix_shell]
symbol = ' '
format = '\[[$symbol$state( \($name\))]($style)\]'

[nodejs]
symbol = ' '
format = '\[[$symbol($version)]($style)\]'

[os.symbols]
Alpine = ' '
Amazon = ' '
Android = ' '
Arch = ' '
CentOS = ' '
Debian = ' '
DragonFly = ' '
Emscripten = ' '
EndeavourOS = ' '
Fedora = ' '
FreeBSD = ' '
Garuda = '﯑ '
Gentoo = ' '
HardenedBSD = 'ﲊ '
Illumos = ' '
Linux = ' '
Macos = ' '
Manjaro = ' '
Mariner = ' '
MidnightBSD = ' '
Mint = ' '
NetBSD = ' '
NixOS = ' '
OpenBSD = ' '
openSUSE = ' '
OracleLinux = ' '
Pop = ' '
Raspbian = ' '
Redhat = ' '
RedHatEnterprise = ' '
Redox = ' '
Solus = 'ﴱ '
SUSE = ' '
Ubuntu = ' '
Unknown = ' '
Windows = ' '

[os]
format = '\[[$symbol]($style)\]'

[package]
symbol = ' '
format = '\[[$symbol$version]($style)\]'

[pijul_channel]
symbol = '🪺 '
format = '\[[$symbol$channel]($style)\]'

[python]
symbol = ' '
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[rlang]
symbol = 'ﳒ '

[ruby]
symbol = ' '
format = '\[[$symbol($version)]($style)\]'

[rust]
symbol = ' '
format = '\[[$symbol($version)]($style)\]'

[scala]
symbol = ' '
format = '\[[$symbol($version)]($style)\]'

[spack]
symbol = '🅢 '
format = '\[[$symbol$environment]($style)\]'

# Custom
[cmd_duration]
min_time = 500
format = ' [$duration](bold yellow)'
# show_notifications = true
# min_time_to_notify = 5000

